#!/bin/bash
aur_packages=/tmp/aur_packages
explicitly_installed=$(pacman -Qeq)
pkglist=$HOME/manjaro-tools-iso-profiles/community/clone/Packages
clone_profile=$HOME/manjaro-tools-iso-profiles/community/clone/
overlay=$clone_profile/clone-overlay/


generate_template_profile()
{
	cp -r /usr/share/manjaro-tools-iso-profiles $HOME/manjaro-tools-iso-profiles
	cp -r $HOME/manjaro-tools-iso-profiles/minimal/net-minimal $HOME/manjaro-tools-iso-profiles/community/clone
}
aur_pkglist()
{
	pacman -Qqm > $aur_packages
}

generate_pkglist()
{
	pacman -Qeq | grep -v -f $aur_packages > $pkglist
}

clone_settings()
{
for file in $HOME/{.config,.profile,bashrc,zshrc,.conkyrc}; do
	[ -e $HOME/$file ] && cp -r $HOME/$file 
#cp -r $HOME/{.config,.profile,bashrc,zshrc,.conkyrc} cp -r
	#copy /etc/pacman.conf 
}

prepare_system()
{

}
main()
{
	prepare_system
	mkdir clone && cd clone
	generate_template_profile
	generate_pkglist
	clone_settings
	aur_pkglist
	if [ $(cat $aur_packages | wc -l) -gt 0]; then
		mkrepo
		cat $aur_packages >> $pkglist
	else
		echo -e "no aur packages installed, proceeding as normal"
	fi
	$EDITOR $profilesettings #choose kernel and other settings
	$EDITOR $pkglist #check that right packages are there
	$EDITOR $livecdpackages #choose your installer
}
