#!/bin/bash
aur_packages=/tmp/aur_packages
explicitly_installed=$(pacman -Qeq)

clone_profile=$HOME/manjaro-tools-iso-profiles/community/clone/
overlay=$clone_profile/clone-overlay/

pkglist=$clone_profile/Packages-clone
[ $(uname -m) = i686 ] && bitness=default || bitness=multilib

generate_template_profile()
{
	cp -r /usr/share/manjaro-tools-iso-profiles $HOME/manjaro-tools-iso-profiles
	cp -r $HOME/manjaro-tools-iso-profiles/minimal/net-minimal $HOME/manjaro-tools-iso-profiles/community/clone
	rm $clone_profile/Packages-Net-minimal
	mv $clone_profile/net-minimal-overlay $overlay
}

aur_pkglist()
{
	pacman -Qqm > $aur_packages
}

generate_pkglist()
{
	pacman -Qeq | grep -v -f $aur_packages > $pkglist
}

clone_settings()
{
for file in .config .profile .zprofile .bashrc .zshrc .conkyrc ; do
	[ -e $HOME/$file ] && cp -r $HOME/$file $overlay/etc/skel/$file
done

#remove browser data and similar stuff
for stuff in $files_to_remove ; do
	[ -e $overlay/etc/skel/$stuff ] && r -rf $overlay/etc/skel/$stuff
done
	cp /etc/pacman.conf $clone_profile/pacman-$bitness.conf
}

prepare_system()
{

}
main()
{
	prepare_system
	mkdir clone && cd clone
	generate_template_profile
	generate_pkglist
	clone_settings
	aur_pkglist
	if [ $(cat $aur_packages | wc -l) -gt 0]; then
		mkrepo
		cat $aur_packages >> $pkglist
	else
		echo -e "no aur packages installed, proceeding as normal"
	fi
	$EDITOR $profilesettings #choose kernel and other settings
	$EDITOR $pkglist #check that right packages are there
	$EDITOR $livecdpackages #choose your installer
}
